### ISSUE TITLE
Rails Bootstrap Navbar

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#1]
I like using [Rails Bootstrap Navbar](https://github.com/bootstrap-ruby/rails-bootstrap-navbar) for creating Bootstrap navbars.  Does this look like it would be fine to do?

**Comment by cg505** [comment]
Given that we already have a functional navbar, it seems a little redundant.

**Comment by cg505** [comment]
I can see the benefits, though. If you want to do that, go ahead.

**Comment by Sammidysam** [comment]
Work for this will be done on the `rails-bootstrap-navbar` branch.  It should be finished pretty quickly once I get to writing the navbar.

**Comment by Sammidysam** [comment]
The work is almost done.  It can be merged after figuring out how to put the logged in or not text outside of the collapse section of the navbar.

**Comment by cg505** [comment]
Ehh, I wouldn't really worry about it.

**Comment by Sammidysam** [comment]
So merge now?

**Comment by cg505** [comment]
I think it's fine.

**Comment by Sammidysam** [comment]
Merging.

**Comment by Sammidysam** [comment]
I will wait to delete the branch until the issue I opened regarding the gem is closed.
