### ISSUE TITLE
Change "for today and tomorrow" to "for this week"

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#10]
I know of a lot of people who plan on a week-by-week basis. Perhaps (in docket#index) we should create a table and divide it into days, with today at the top and the rest of the week below it.

**Comment by Sammidysam** [comment]
Yep, I was thinking that too.  We could make the table like the docket---assignments take up 4/5, events 1/5 on right---then thick horizontal lines between the days.

Better yet, we could let the users configure how their dockets look.

**Comment by rye** [comment]
Yeah. I'm thinking letting them configure through a menu and then storing their stuff as JSON.

**Comment by rye** [comment]
Maybe after 0.1.0, though.

**Comment by Sammidysam** [comment]
**Definitely** after 0.1.0.

**Comment by cg505** [comment]
That sounds like a good idea. I'm not really very good at this whole UX stuff, so go ahead.

**Comment by Sammidysam** [comment]
We should wait until after 0.1.0, though, right?  For now we just need to take the current interface and make sure everything lists correctly.

**Comment by cg505** [comment]
Yeah.

**Comment by rye** [comment]
This is taken care of with the new design (paneled layout)
