### ISSUE TITLE
Add a new user link

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#11]
This needs to be done. Link should go on log in page.

**Comment by Sammidysam** [comment]
Is this just a register button, and that's it?  I feel like it might be better to go on the far right of the navbar when nobody is logged in.  It would be easier to see that way, considering that they look to the right of the navbar.  Three other options are right next to the "Log in" button to the right, to the far right of the log in button where the entry box ends, and below the log in button.

Thoughts, @four04?

**Comment by rye** [comment]
Fixed in 4a5ac868397fd4a29359ecf4fb6ede8ce6bcf5ef.

**Comment by Sammidysam** [comment]
The solution looks good.
