### ISSUE TITLE
Docket Interface

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#13]
We should add a docket interface (like a table). Color-code it, too. And make it pretty.

**Comment by Sammidysam** [comment]
I think that we should have the left 75% (`col-md-9`) be the assignments and the right 25% (`col-md-3`) be the events for each day.  The events will be a list like in the physical docket, and the assignments will be ordered by class.  The classes are ordered by period number.  There will be the class name, and then the assignments will be below, indented.  It would be like this.

```
English 9 Honors
    Biography Response (January 6)
    Final 3 Minute Fiction (January 10)
```

I would put more classes in the example, but I only have homework in English right now.  The class name and likely assignments would be links.  We would also be able to hide or show assignments for each class, similar to how Org-Mode does that.  The tests for the day should come before the list of assignments.  They should also be ordered by class, too, and possibly as the day goes on they disappear depending on what the time is.

**Comment by rye** [comment]
FTR (**F**or **T**he **R**ecord): The changes described here are partially implemented as of 6cc4d1b4162a065c24c9e4b9dbc9c5a4c1e21bf0. Still to be done:
- [x] Add Event display.
- [x] Move everything around and make it more compact.
- [x] Group assignments and exams by class.
- [x] Sort by type (exams first, then assignments)
- [x] Sort groupings (prev. 2 points) by class hour.
- [x] Simplify and optimize backend.

**Comment by rye** [comment]
The interface would then display the class to the left of all of the things taking place in that day in that class, and use a vertically-cell-spanning table cell to display the name of that class.

**Comment by rye** [comment]
Everything relating to this looks pretty nice to me :atm:.
