### ISSUE TITLE
Baseline Design

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#14]
We should probably select some kind of non-obnoxious color scheme, and start implementing it. I'd like something other than {black,grey}-on-white, preferably something where we've got a slightly or significantly darker background. I think pastel colors would also be a good thing. Opinions?

**Comment by rye** [comment]
I'd say some kind of bootswatch-y thing would work.

Personally, I love raw [Cyborg](http://bootswatch.com/cyborg/), but it's too dark for most. [Flatly](http://bootswatch.com/flatly/) and [Cosmo](http://bootswatch.com/cosmo/) are pretty nice, too. I've used [Slate](http://bootswatch.com/slate/) in the past, but, again, it may be too dark for most. I suppose [Yeti](http://bootswatch.com/yeti/) works too.

Any ideas?

**Comment by rye** [comment]
The advantage of using something from bootswatch is that we don't have to do any work. :)

**Comment by cg505** [comment]
If we do use bootswatch, we should use [this gem](https://github.com/maxim/bootswatch-rails) for sass support.

**Comment by rye** [comment]
Which theme would we like? I'll go ahead and apply it if I get a decision made in the next half-hour.

**Comment by Sammidysam** [comment]
[Journal](http://bootswatch.com/journal/) says that it is "[c]risp like a new sheet of paper".  I think we are kind of going for a feeling of the physical docket, so maybe since it compared itself to paper it would be good to use.  Are we looking to make it feel somewhat like paper?  If so, dark background themes are immediately out of being considered.

**Comment by rye** [comment]
No, I would not say realism is a goal here. And nobody cares what the name of the theme is that we're using. Personally, Journal is one of my least-favorites of the light themes.

**Comment by Sammidysam** [comment]
Ah, okay.  I mentioned it because it sounded like it was built to have a paper-like feel, so I thought that it would work well if that is what we were going for.  Should I list themes that I like from the list of all themes or only the themes that you have said that you like?

**Comment by rye** [comment]
I would say give an ordered list in descending order of preference.

EDIT: From all themes.

**Comment by Sammidysam** [comment]
That did not answer my question, but okay.

**Comment by rye** [comment]
I'd like this to be done for v0.2.0.

**Comment by Sammidysam** [comment]
Ah, good.  I didn't see your edit, but now I do.  I'll figure out my favorites very soon.

**Comment by Sammidysam** [comment]
1. Cosmo
2. Cerulean
3. Yeti

Cerulean is really pretty, but I don't think that blue would work tremendously well for this.  I feel like black is better.  That is why I put it as 2 instead of 1.

**Comment by rye** [comment]
I like Cosmo, as well. @cg505?

**Comment by rye** [comment]
I will branch this off of `v0.2.0` and will do the following:
- [ ] add `bootswatch-rails` gem
- [ ] add imports for the Cosmo gem (We can change it later if we don't like it)

We'll see what needs to happen after that.

EDIT: The branch will be called `theme`

**Comment by cg505** [comment]
1. Yeti
2. Cosmo
3. Default BS
4. Flatly

**Comment by rye** [comment]
I actually like Yeti more; I suppose I'll use that one. We can change it later, as I said. They're quite similar.

**Comment by cg505** [comment]
I'm not a huge fan of Cerulean, mainly because I don't like the header font or color. I also really don't have a problem with default bootstrap. The only reason I put Cosmo higher is that I don't like `btn-info` being blue when `btn-success` is. However, I like Yeti enough that it doesn't really matter.

**Comment by rye** [comment]
Can you explain for what reason SCSS is complaining about not being able to find or load the added stuff @ 16604b5998793c836f455e478917e4f62d6ed614?

**Comment by cg505** [comment]
Did you try loading yeti after bootstrap?

**Comment by rye** [comment]
Just now, yes. It still fails.

```
File to import not found or unreadable: bootswatch/yeti/variables.
Load paths:
  /home/kristofer/git/github/kotct/docket/app/assets/images
  /home/kristofer/git/github/kotct/docket/app/assets/javascripts
  /home/kristofer/git/github/kotct/docket/app/assets/stylesheets
  /home/kristofer/git/github/kotct/docket/vendor/assets/javascripts
  /home/kristofer/git/github/kotct/docket/vendor/assets/stylesheets
  /usr/local/lib/ruby/gems/2.1.0/gems/jquery-turbolinks-2.0.1/vendor/assets/javascripts
  /usr/local/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.0.3.0/vendor/assets/fonts
  /usr/local/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.0.3.0/vendor/assets/javascripts
  /usr/local/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.0.3.0/vendor/assets/stylesheets
  /usr/local/lib/ruby/gems/2.1.0/gems/turbolinks-2.1.0/lib/assets/javascripts
  /usr/local/lib/ruby/gems/2.1.0/gems/jquery-rails-3.0.4/vendor/assets/javascripts
  /usr/local/lib/ruby/gems/2.1.0/gems/coffee-rails-4.0.1/lib/assets/javascripts
  /usr/local/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.0.3.0/vendor/assets/stylesheets
  (in /home/kristofer/git/github/kotct/docket/app/assets/stylesheets/application.css.scss:17)
```

**Comment by cg505** [comment]
And you bundle installed and restarted the server?

**Comment by rye** [comment]
Yep, I've done that after every change and I still get the same error.

**Comment by cg505** [comment]
If you read the README for that gem, Yeti isn't on the list of supported bootswatches.

**Comment by rye** [comment]
The same error occurs when using Cosmo, which _is_ on the list of supported bootswatches. This is, of course, after re-`bundle install`-ing and restarting the rails server, both actions of which were taken out for good measure.

**Comment by Sammidysam** [comment]
See if it works when you put the code in a separate file.  application.css.scss is not typically supposed to be used for everything, I think.

**Comment by Sammidysam** [comment]
I think you need to remove the commented lines at the beginning.  See the sample file in the readme.

**Comment by rye** [comment]
I removed the commented lines (and followed the "good measure" procedure defined in my previous comment) and it did not work. What other file would you suggest?

**Comment by rye** [comment]
I say this because it seems that most other `.css.scss` files appear to be either associated with a scaffold or designed to govern over said other `.css.scss` files.

**Comment by Sammidysam** [comment]
Try copying the example file (since we use GitHub, we can easily recover the old file).  Did you?  See if that works.

**Comment by rye** [comment]
I see no example file; can you link it to me? I've done everything in the README of `bootswatch-rails`, yet it's still not working properly. Could it possibly be something with the `stylesheet_link_tag` in `layouts#application`?

**Comment by Sammidysam** [comment]
This is the example `application.css.scss`

```
// Example using 'Cerulean' bootswatch
//
// First import journal variables
@import "bootswatch/cerulean/variables";

// Then bootstrap itself
@import "bootstrap";

// Bootstrap body padding for fixed navbar
body { padding-top: 60px; }

// Responsive styles go here in case you want them
@import "bootstrap-responsive";

// And finally bootswatch style itself
@import "bootswatch/cerulean/bootswatch";

// Whatever application styles you have go last
@import "base";
```

**Comment by rye** [comment]
No, even the example code does not work. What that says to me is that it is, indeed, a problem with the `stylesheet_link_tag`.

**Comment by Sammidysam** [comment]
You should probably just open an issue.

**Comment by Sammidysam** [comment]
Due to my failure at English and being specific, #27 was created.  It was not really necessary, but we can work with it anyway.  Once it is closed and Bootswatch is implemented, this can be closed.

**Comment by rye** [comment]
It looks like we're done.
