### ISSUE TITLE
Personal Assignments

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#15]
I sometimes put assignments in my docket that are not generally for all others in the class.  For example, on Thursday (the last Thursday in which there was school) under Orchestra I put "Think about pit" (yeah, I was late with getting that in).  We should allow users to make an assignment in a class that is only visible to them.

**Comment by cg505** [comment]
We could do this for 0.3.0. It would probably be best done as another scaffold (or maybe just a model).

**Comment by Sammidysam** [comment]
I can understand it being better for a later version, considering that it deals more with assignments than with the docket.  What do you think, @four04?

**Comment by cg505** [comment]
In retrospect, it would be a somewhat small feature. I can see it being done as either 0.2.0 or 0.3.0.

**Comment by rye** [comment]
Personally, I think we should call this kind of scaffold or whatever a `Note`. Notes would be personal, yes, so they would only have `name:string description:text` as per the usual specification and then `user_id:integer` and `classroom_id:integer`.

**Comment by rye** [comment]
Should we move this from the `Version 0.2.0` milestone into the `Planning` branch considering that it does not have a set-in-stone point of implementation?

**Comment by Sammidysam** [comment]
To your first comment, I think that is fine.  We could also add, to the assignment model, a user id of the creator and a private boolean if we wanted to treat them as assignments.  But I agree making a separate scaffold would probably be easier.  To your second comment, yes.

**Comment by cg505** [comment]
Also, it would be acceptable for `classroom_id` to be `nil`.

**Comment by Sammidysam** [comment]
Indeed.  We could put the class-less notes at the bottom.
