### ISSUE TITLE
Accommodate for Non-Procrastinators

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#16]
For overly-large projects, some would say it is important to start working ahead-of-time on them.

In order to accommodate for these people, I think three things need to be done.
- [ ] Allow for displaying of future or past weeks in the docket (it is important regardless) for planning or quick view purposes.
- [ ] Implement rendering of future events somehow (_see below_)
- [ ] Figure out sorting.

My idea for this is to have a system where the system looks at the total amount of time that was allotted for a given assignment (i.e. looks at date of creation or a new separate field `assigned_date`). It would then, for a given day, calculate what fraction of the given time period has passed and then will sort all of the assignments for a given day in a given class by that value (which will be expressed as a decimal between `0.0` and `1.0` or as a fraction `[days since assignment] / [total days allotted]` [which would be easier to display, but for calculations would be expressed as a decimal].

With this system, the user then specifies at which threshold they wish to start seeing projects that are due in the future (for example, when one is half-way to the due-date or closer, then it starts getting displayed).

We could also weight according to point values of each project, but that's getting into semantics which I'm not really keen on implementing at this point.

**Comment by Sammidysam** [comment]
Docket view configuration is probably the most important, so that everybody's idea on how the docket best looks can be implemented and then the users can decide which one they like best.  It can also be something that we add in 0.2.0, too.

**Comment by cg505** [comment]
I agree with @Sammidysam's last sentence: this should go for 0.2.0.

First of all, we should have the docket be paginated (http://getbootstrap.com/components/#pagination-pager) so that people can move forward or backwards at will. 
Somewhere else on the page, we would have @four04's suggested long-term assignment list. I like the idea very much. The only problems I can think of are 1) I don't know where we would put it and 2) people might not know how to use the assigned_date field, so if someone puts in all of Watson's assignments, halfway through the semester the long-term list would contain every assignment left for that semester.

**Comment by rye** [comment]
On the _form is it possible that we could just put "date assigned" as the
label for the assigned_date field?

// Kristofer "four04" Rye

**Comment by cg505** [comment]
Let me explain my example more thoroughly: a person is putting in all the assignments in Watson's packet. They don't know what the "date assigned" field is used for or they think that they should put the date of assignment for all of these assignments as the first day of school. Then we have bad things happening.

Probably an issue that we don't need to worry about, realistically, though.

**Comment by cg505** [comment]
So is this going in 0.2.0?

**Comment by rye** [comment]
I'd say we should make some screencasts for teh noobies and explain this stuff once v1.0 rolls around, to alleviate the idiocy problem.

I think this should go into v0.3.0.

**Comment by Sammidysam** [comment]
What are we talking about going into what version?  I was not talking about the main points in the issue with my first comment; I was just adding something that I feel is more important.  Here was a bad place for that.  But anyway, I am curious what we were all talking about.  The pronouns got lost.

**Comment by rye** [comment]
The list of accomodations and fixes and your comment will go into v0.3.0 (unless a majority movement is made towards 0.2.0)

**Comment by cg505** [comment]
Yeah, that was my inability to read again. (I'm starting to reach @samercier levels.)

**Comment by Sammidysam** [comment]
I think the docket view configuration would be better suited in 0.2.0.  But the others make sense for 0.3.0, or possibly 0.4.0 if we put our focus somewhere else.

**Comment by rye** [comment]
We should modify the backend to support selecting weeks (blocks of time) and I should work on getting the front-end to look pretty. Then, the params need to be scanned to determine which week to operate on.

Plan in place, I'll work on this soon.
