### ISSUE TITLE
CanCan

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#17]
Shall I do this as a patch?

**Comment by rye** [comment]
I would say so. Even better, a physical `.patch` file would make me very happy. :)

But, I would say just do it as `v0.1.1`

EDIT: I'd ask that you try to make it as merge-able as possible.

**Comment by cg505** [comment]
I can just branch off of master and do it. It should be fairly painless.

**Comment by cg505** [comment]
We need to test `cancan` now.
