### ISSUE TITLE
Order Items

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#18]
We should order items for v0.1.1.  Here is how.
- Teachers - order by last name (can we do that?)
- Courses - order by name
- Classes - order by course

**Comment by Sammidysam** [comment]
I updated how we should order items.

**Comment by cg505** [comment]
> order by course

What does that mean?

**Comment by Sammidysam** [comment]
All classes from course x will be listed, sorted by period.  So, for example, Physical Education II period 7 will be followed by Physical Education II period 8.  The courses can be ordered by name.  So all classes in Chemistry I Honors will be above Physical Education II.  Does that make sense?

**Comment by Sammidysam** [comment]
We should also sort a teacher's classes by period number.

**Comment by Sammidysam** [comment]
Fixed by f64607a26293c2704a691aae44ff5f8b0ccd01bb.  Closing.
