### ISSUE TITLE
v0.1.1

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#19]
These are the things that are slated to go in 0.1.1 (edit as needed):
- [x] `master`: Favicon
- [x] `cancan`: CanCan (see #17)
- [x] `sidebars`: Schedule in right sidebar? ~~(still undecided whether this will go into the release)~~ (EDIT: going into release)
- [x] `fixes`: Sort things in indexes and such (see #18)

Bugfixes:
- [x] `fixes`: Case-insensitivity on autocomplete text boxes
- [x] `master`/`fixes`: `relevant_date` thing
- [x] `fixes`: Join/leave `redirect_url` param
- [x] `fixes`: Mobile `meta` tag

**Comment by cg505** [comment]
So is this release ready?

**Comment by cg505** [comment]
And are we adding the sidebar schedule?

**Comment by rye** [comment]
It should be fine. And v0.1.1 looks release-ready.

**Comment by rye** [comment]
Which branches need to be merged? And where to?

**Comment by cg505** [comment]
All the mentioned branches, to master. I'll do it.

**Comment by rye** [comment]
Okay. :+1:

**Comment by cg505** [comment]
Sorry it's taking so long, having fun undoing the sidebars merge (3d91425bc4a48e20303ca18e6a855450a7131b2c).

**Comment by cg505** [comment]
I think I fixed it now, commencing merges.

**Comment by cg505** [comment]
Release created.

**Comment by Sammidysam** [comment]
Are we going to put the changelog into `CHANGELOG.md` or only the release description?  I suggest we copy it to `CHANGELOG.md` to keep a list of the changelog for every new version.

**Comment by rye** [comment]
I second that.

**Comment by Sammidysam** [comment]
Done.  It is on the documentation branch.
