### ISSUE TITLE
Versions/Releases?

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#2]
Are we going to use version numbers and releases for this program?

**Comment by cg505** [comment]
I was under the impression that we would. However, at the current rate of development, we should be able to skip sub-sub-versions. v0.1 should be available soon.

**Comment by Sammidysam** [comment]
If we are planning on using releases, I would prefer that we use more branches and then merge when we are going to release a new version, similar to Smart Create.  If that is inconvenient, we can just ignore versions.  I'm not as concerned about that when this is just a web application.

Therefore, if we are going to use versions, we should make a `0.0.1` release right now on the current commit of `master`.  Then we should use branches for all new changes, and then merge the branch into `master` for a new release.

We might also want to make a plan of the development process.  Then we know what exactly we should work on.

**Comment by cg505** [comment]
Yeah, I've been kind of failing on the whole branching stuff, but I plan on doing that for further development.

As I mentioned above, given how close we are to having most of the important features implemented, I think it would be better to hold off just a few days and then release v0.1.

**Comment by cg505** [comment]
A few days being like until Friday-ish.

**Comment by Sammidysam** [comment]
Okay, that will do.  But from `0.1.0` on, we should definitely focus on using branches.

I think it may be good to make a list of important features, though, so that everyone knows what we are working for.  Because we have figured out our plan on this matter, this issue will be closed.
