### ISSUE TITLE
Docket Views

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#21]
We should allow three (maybe four) different views for the docket, and the user should be able to specify which view they want by default.  If there are other views that would be good, let me know.  They are
- week view, currently implemented
- **MAYBE** month view, like what the docket has near the end
- day view, just one day of the week view being shown
- all view, day view showing all future assignments
  
  An example of this is
  
  ```
  English 9 Honors:
      Biography Response (January 6)
      Final 3 Minute Fiction (January 10)
  ```
  
  so in the style `assignment (due date)`, and the due date would not appear if the item is due the next day.  This view is convenient for looking at what is due the soonest for each class (and, if too many assignments are there, one can just hide all classes they are not looking at, which we still need to add).

Of course, we need next and previous buttons with all of the views.

**Comment by cg505** [comment]
I think this should be a part of 0.2.0

**Comment by Sammidysam** [comment]
I agree.  We can add views for 0.2.0, then configuration of the views for 0.3.0.

**Comment by rye** [comment]
These would just be further controller "actions," correct? Like index,
except with different names, of course...

**Comment by Sammidysam** [comment]
Yep.  For day, we can specify a way in the routes to get the date, so that one can use a path such as `/docket/day/2014/02/01`, then for the all view we can just set a variable within it or something.  Then we just work in the controller with it.  We will also need to start specifying dates for the month view now that we want to eventually add forward and back buttons.

**Comment by rye** [comment]
I think this should probably wait until we have an existing system for user configuration, considering that the week (to be displayed) will probably change with the user configuration, and so start dates and such may cause problems.

**Comment by Sammidysam** [comment]
I do not think that that will cause much of a problem.  Besides, the week view is already created.

**Comment by rye** [comment]
I think this would be much more of a change than the change described in #25, and as such should be pushed to version 0.3.0. I've already postponed the `v0.2.0` release for long enough (from last Friday, IIRC), and the views would fit nicely in with user configuration. Pre-implementing stuff that will likely just get re-implemented sounds bad. I'll move this to the version 0.3.0 milestone.

**Comment by Sammidysam** [comment]
User configuration is actually not needed at all for docket views except for the default view to be used when a user logs in.  Therefore, I feel like it would fit 0.2.0 very well, considering that the focus for 0.2.0 was making the docket very pretty.  However, if I really felt like that I should've programmed it myself, considering that you did not see the huge need.  It's not a big deal to have it delayed considering that it will indeed be implemented eventually.
