### ISSUE TITLE
User Configuration

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#23]
While this seems like it will be a very large change, we need to implement this for the masses to be happy. We touched on it before, but we haven't really discussed it _per se_.

What will be important about this is that we keep it both simple and powerful. I like the idea of having a JavaScript interface which is a form and lets the user configure their things, whilst generating JSON which is what is actually stored in the database. We should **not** create separate fields for every thing, as migrating will be painful and it will be more pointless.

When the user is created, they would simply get a default JSON configuration (we would create that), with the option to configure displayed once they log in.

@Sammidysam has provided a nice example of what kinds of things we might put in this configuration (at #21). I'd recommend not only having that but also letting the user configure things like raw colors or selecting between predefined color schemes (i.e. a "light" theme, and a "dark" theme). We should also let them do stuff as described in #20, where they can select things like what day the week starts on.

Other ideas include: date formats, and the future-application threshold described in #16.

We should set this as a priority.

**Comment by cg505** [comment]
Why don't we just create a config table in the db, and each column in the table represents an option, instead of messing around with JSON?

**Comment by Sammidysam** [comment]
Using the database would probably be faster than converting JSON into a Ruby hash.  I think this because I think that the JSON library for Ruby is programmed in Ruby, whereas the database library is programmed in C.

**Comment by cg505** [comment]
Should this be going for 0.2.0?

**Comment by rye** [comment]
I think so. I can get started on it.

So we'd add a `config` table? The fields would be `user_id:integer` for whichever user it corresponds to, and then everything else would be whatever it needs to be? That works, I suppose.

Which of the following would best describe it?
- assets
- controller
- generator
- helper
- integration_test
- jbuilder
- mailer
- migration
- model
- resource
- scaffold
- scaffold_controller
- task

**Comment by cg505** [comment]
I think we should just start with user_id. We will add more column via migrations as we need them.

I think this looks helpful: http://guides.rubyonrails.org/routing.html#singular-resources.

So,

``` sh
rails g model config user_id:integer
rails g controller config show edit update # I don't think we want new, index, or destroy
```

Then we should try adding `resource :config` (per the link above) to the routefile, but it may not work since we don't have an index, new, or destroy. We may just have to manually add each individual route.

Configs should be automatically created when the user is. We may be able to, in the migration, make configs for all existing users. Iff not, we can make a rakefile.

When adding new columns, we will probably want them to have default values.  See here: http://api.rubyonrails.org/classes/ActiveRecord/Migration.html#label-Using+a+model+after+changing+its+table

**Comment by cg505** [comment]
So is this going in 0.2.0? It would make sense to put it there, but at the same time it seems a little big.

**Comment by rye** [comment]
I think what with all of the improvements that have already been made for v0.2.0, it would make sense to put these changes into v0.3.0.

**Comment by Sammidysam** [comment]
Yeah, I think that this can be our focus for 0.3.0.  It will be a big change.

**Comment by rye** [comment]
Okay, I'm throwing this into the v0.3.0 milestone

**Comment by Sammidysam** [comment]
Actually, maybe we should work on improving events, assignments, and exams for 0.3.0 and save this for 0.4.0.  What do you think?

**Comment by rye** [comment]
No, I think this needs to be added as soon as possible.

**Comment by Sammidysam** [comment]
Okay, I guess.  Though I feel like 0.3.0 would be relatively quick if we just improved events, assignments, and exams anyway.

**Comment by rye** [comment]
Or we could do the two together in the same release.

**Comment by Sammidysam** [comment]
Maybe.  We can revisit our focus when we finish 0.2.0.

**Comment by Sammidysam** [comment]
In ee47f56ebf7aede0550541d3177d512a27f7e418 I added showing a user's schedule, and we should add a user configuring whether others can view their schedule or not.  It'll just be a boolean.

**Comment by rye** [comment]
@cg505, I'm working on this now. I'll throw this into branch `user-configuration`

**Comment by rye** [comment]
And I'll put it into `v0.2.0`, just for the heck of it. It should be pretty easy.

**Comment by rye** [comment]
How does [this](http://stackoverflow.com/a/1683197/1968483) look, @cg505 / @Sammidysam?

Also, [this](https://github.com/cjbottaro/has_easy)?

**Comment by rye** [comment]
I think the latter looks like it would be easier to use, and it appears more fully-featured.

**Comment by rye** [comment]
For now I guess I'll add that to the project.
