### ISSUE TITLE
Two Coding Style Questions

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#24]
What is preferred?

Single or double quotes for a Ruby string?

`class: "thing"` or `:class => "thing"`?

**Comment by cg505** [comment]
Double, and for the second I don't have a strong preference, but I would generally prefer the first (newer) syntax.

**Comment by cg505** [comment]
@four04?

**Comment by rye** [comment]
Double quotes, always. If you see something autogenerated that uses single, change it. And I would prefer the newer syntax, especially for things like `link_to` tags (where I believe you saw that)

**Comment by Sammidysam** [comment]
Okay, we will use double quotes and the newer syntax then.  Thanks for letting me know.
