### ISSUE TITLE
Global events

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#25]
Some events affect the entire student population, such as "no school" or "first day of school". There should be a way to mark these as such so that these events show up in all dockets.

**Comment by Sammidysam** [comment]
I think that we can wait until 0.3.0 for this, considering it is not part of our 0.2.0 focus.

**Comment by rye** [comment]
This would be quite simple; all we would need is to make it so that all users have joined the event by default.

Personally, I would like to also see the note thing get implemented so that users can have their personal things.

**Comment by rye** [comment]
And I think this can go into `v0.2.0`. That is what we are currently working on.

**Comment by Sammidysam** [comment]
I don't think it needs to go into 0.2.0 by any means.  If it is done, then that is okay, but it would make more sense for 0.3.0.

**Comment by Sammidysam** [comment]
Is it okay to switch this to 0.3.0?  Or maybe even 0.4.0, if configuration is big enough to be a whole minor version.

**Comment by rye** [comment]
I don't want to plan too far ahead, and planning at this point for even the `v0.3.0` release is too early. Considering that this is such an easy modification, it stays in `v0.2.0`.

**Comment by Sammidysam** [comment]
I think having an idea of what the 0.3.0 focus will be is not a bad thing to have.  It looks like it will be user configuration, so really, global events is in a kind of bad spot of not really fitting anywhere.  It is the same thing with marking assignments as complete.  Granted, the 0.3.0 focus has not been determined yet, so we still do not know what it will be.  Maybe it will be fixing up events, assignments, and such (we can do the two listed before as well as personal assignments).  I am just not sure how many features away from our focus for the release that we want to have.

**Comment by rye** [comment]
Again, since setting up a checkbox that a person with the right permissions can check to make it such that when they submit their new event everyone is automatically joined will be rather simple, this should stay in `v0.2.0`.

**Comment by Sammidysam** [comment]
Since this is easy to implement, why not use a patch version?  I will be happy because we will not be bundling a feature outside the focus in the minor version associated with the focus, and you will be happy because we will not delay adding the new feature.

**Comment by rye** [comment]
Since it seems like we're nearing a minor release, it would be nice to just throw it in there. I don't want to make a special patch release _just_ for a feature, as patch releases aren't really for features and we don't have any bug fixes that we've made to the existing version.

**Comment by Sammidysam** [comment]
Yeah, now that I think about, we can just include it in the minor version.  As long as by the changelog it still looks like our focus was our focus, it's fine.  Feel free to do work on this.  I would personally prefer a `global` flag, so that users cannot leave the event.  Though, we could check if all users have joined the event.  That wouldn't always work, though.

**Comment by rye** [comment]
Actually, your `global` idea works better. It'd be pretty easy to write.

**Comment by rye** [comment]
This is completed as of: bb69d3591ca67d699f0d73b69b8b4b6cd9e7ac7d. I may add some changes later, but it's done now.

Thoughts before I merge?

**Comment by rye** [comment]
I'll be merging this either at lunch or around 15:00 today, so send input before then if you see any glaring problems.

**Comment by rye** [comment]
The word from @Sammidysam is that this is okay. For now I'll just go ahead and merge it, but we shouldn't delete the branch until we're sure that there are no problems or anything.

**Comment by rye** [comment]
And considering that this thing is now mostly implemented, I'm going to close the issue.

**Comment by Sammidysam** [comment]
After running it, it looks like it works fine.
