### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#26]
The following branches look dead, and I think the should be deleted:
- ~~`rails-bootstrap-navbar`~~
- ~~`cancan`~~

Also, you should take a look at the network graph. It's beautiful.

EDIT: As you need branches to be removed, add them as bullet points. As they are removed, strike them through.

**Comment by rye** [comment]
I think both of them should be okay to kill off. Just make sure their parents have their commits merged into them.

Dat network graph. So pretty. I wish I could download it.

**Comment by Sammidysam** [comment]
Considering I have not been doing anything towards submitting a pull request to Rails Bootstrap Navbar, the branch can be deleted.  I don't think that we even need to put items outside of the collapseable portion of the navbar anymore, anyway.

**Comment by Sammidysam** [comment]
We can resolve this once 0.2.0 is released.

**Comment by rye** [comment]
I'm going to delete `rails-bootstrap-navbar` and `cancan`.

EDIT: Done. See the EDIT I made to the original issue.

**Comment by rye** [comment]
Since we have a new branch scheme that has been proposed and will be implemented, I am closing this issue due to age and replacement.

**Comment by cg505** [comment]
You didn't close it.

**Comment by cg505** [comment]
I did.

**Comment by rye** [comment]
Coo'
