### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#30]
Our physical docket has a quote of the week each week, and when we were first planning this program I mentioned that we should have quotes in it as well.  Quotes are fun.  I then looked for a gem that could work, and found [wikiquote](http://rubygems.org/gems/wikiquote).  After installing, I realized that the quote was formatted horribly, so I decided that I needed to modify the code to not be horrible.  [This](https://github.com/hemanth/wikiquote-gem/pull/1) was the result, and now [this](http://pastebin.com/jc1pBep0) is an example of how it can be used now.  That is very usable, so it could be good to use.

Why it could not be good to use is that how the quote of the day is gotten is very hacky and could very easily break.  [This](https://github.com/hemanth/wikiquote-gem/blob/master/lib/wikiquote.rb#L17-25) is how it is done.  It leads to the horrible formatting of the text initially.  As long as WikiQuote doesn't change their layout (which they have not since the gem was first created in May of 2012), it will stay working, _hopefully_.  The code is all pretty weird and could break really easily.  If we use it or depends on if we want to take the risk of it suddenly breaking.  Another bad thing about it is that it is quite slow.  Just running `wikiquote` (the executable) took me 1.332 seconds.  That is not very good at all.  Therefore, if we wanted to use it, we would probably want to save the quote to the database each day to not need to slow down the page generation.  Do we want to use this gem?

If we added support for this, it would work as another patch version.

**Comment by hemanth** [comment]
@Sammidysam :+1: Seems like an end to end solution, saving to db would not be a tough task, we can patch it!

**Comment by rye** [comment]
I would say that this should go into `v0.2.0`, considering that it's not really a fix but more of a feature. If you're interested in adding it, by all means that's something that could easily go onto the top of the week view. I would avoid taking up too much space, and it should integrate nicely.

Of course, the problem that I could see us facing is that we may have to filter out some of the quotes on WikiQuote (I'm totally not sure). Many of the quotes in our paper docket are, as they say, "inspirational," and so we may want to go for inspirational quotes as opposed to just general quotes. That's something to consider, nonetheless.

**Comment by hemanth** [comment]
I agree with the version.
Space hmm...we can clear the db once in a while?
Filtering is not so easy, there must be an API out there?

**Comment by Sammidysam** [comment]
@kryestofer I believe all of the quotes are trying to be inspirational.  At least, all that I have seen have been.  But, this is our program, not our school's, which allows us to do what we prefer.  I prefer a larger variety of quotes.  Do you agree that saving in the database would be good?

**Comment by rye** [comment]
Saving in the database would probably be helpful.
