### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#31]
Do we want to put the version number and GitHub URL in the footer?  I did some work in cb07e4aa54ba0236b0a643e6b5f192b1742ec988, but we should probably switch to a sticky footer.

**Comment by rye** [comment]
I would suggest a debug hash as well, we have [one](https://github.com/team461WBI/website/blob/master/app/views/partials/_footer.html.erb#L56) on the BoilerInvasion website (that variable is defined [here](https://github.com/team461WBI/website/blob/master/app/controllers/application_controller.rb#L20)). Maybe something that's more useful or decodable (for example, latest commit hash as the first 16 characters, version number in hexadecimal, current user's ID in hexadecimal, that kind of stuff).

**Comment by rye** [comment]
We should probably put human-readable, but, with my idea, we could just tell people to copy that into any bug reports.

**Comment by Sammidysam** [comment]
That sounds like a good idea.

**Comment by Sammidysam** [comment]
I would also like an opinion towards if we should have a sticky footer or if that does not really matter.

**Comment by rye** [comment]
For posterity, define the term _sticky_ footer.

**Comment by Sammidysam** [comment]
The footer will stay at the bottom of the page even when there is not content to force it down to the bottom of the page.  See [this page](http://css-tricks.com/snippets/css/sticky-footer/)'s example.  Even without content, the footer is still at the bottom.

**Comment by rye** [comment]
It would be good, I would say.

**Comment by Sammidysam** [comment]
It won't be easy to implement, I think.

**Comment by rye** [comment]
I will close this issue and create a new one entitled "Sticky Footer" for things regarding this (this one is old and part of it has been implemented).
