### ISSUE TITLE
Some Suggestions for Quick Usage

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#33]
1. ~~Make `exam`'s not admin-only (they appear to be at the moment).~~ [EDIT: added (not tested) as of affc686a82c223216b09ee5add99f855445ca0e0]
2. ~~Add quick assignment/exam/event creation buttons that take you to a page with an extra "classroom" field (`assignment#_form` is usually given a `classroom_id` param, just check for that `classroom_id` and display a field if you don't have it, I think).~~ [EDIT: added a long time ago]

More to come later. If you see something that should be changed, let me know.

**Comment by rye** [comment]
@cg505 and I discussed this today at lunch. We think that the appropriate place for the quick-add buttons would be in either the navbar (as text links (or, I suppose, buttons)) or in xs [button groups](http://getbootstrap.com/components/#btn-groups) in the sidebar. If in the sidebar, we'd likely move the badge to the left and then put the button group on the far right (or have the button group on the left and the badge where it is now).

**Comment by Sammidysam** [comment]
I think that putting buttons in the sidebar would be better.

**Comment by rye** [comment]
The problem is with size; many of the monitors of the school computers cannot display the sidebar and its contents as it stands now.

**Comment by Sammidysam** [comment]
Mobile would also be a problem.

**Comment by Sammidysam** [comment]
We can add a button to the top of the body on the docket page (or any page).  That would work, I think.

**Comment by rye** [comment]
Perhaps a big btn-group that spans the whole page content area for the mobile people?

**Comment by rye** [comment]
I would offer the suggestion of making the large `btn-group` for the mobile users and having a `xs btn-group` in the sidebar for desktop users.

For now, though, I'd say that we should just go for having some links in the navbar, and then maybe some other things.

**Comment by Sammidysam** [comment]
That is a good start.  Maybe it is good to implement it somehow at first, then tweak it in the future.
