### ISSUE TITLE
Duplicate Detection?

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#34]
Raise an alert when submitting a new assignment, exam, or event if there is something in the database already that fuzzy-matches it (or matches certain words) and has the same class and due date (or date, if event).

Either (a): ask for confirmation or (b): submit for moderation (which should be a thing, methinks).

This will help to prevent spam.

**Comment by Sammidysam** [comment]
Should be done eventually, but this won't be necessary to add for awhile.  Just before 1.0.0.

**Comment by cg505** [comment]
Why is this closed?

**Comment by rye** [comment]
Lack of activity.
