### ISSUE TITLE
Mark Things as Completed?

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#37]
This seems like a simple thing (similar to memberships, I suppose) to implement, but it's likely something that will be necessary. The basics are as follows: the thing would have two fields, `user_id` and `assignment_id`, and would be used by the user to mark an assignment as complete.

Completions should be private, IMHO. Perhaps admins will have the ability to see them (for debugging purposes), but I think it's really not that necessary. Considering that we should probably do this without generating any views (i.e. incorporate some buttons into existing forms and displays like a "mark as complete" button on the assignments display)

I think we should wait until we've released the new design to start on this, considering it'll likely integrate much more effectively with the `v0.2` interface than with the `v0.1` interface.

**Comment by rye** [comment]
I would say that we should also consider releasing `v0.2.0` soon. It's ready, to my knowledge.

**Comment by Sammidysam** [comment]
I agree that this should be done.  I was thinking of opening an issue for the same thing awhile back.
