### ISSUE TITLE
Pressing Back in Some Views Takes to a Different Place

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#38]
At many views (assignments#show, classrooms#show, {[etc.]}#show), pressing the "back" button takes the user to a page other than that which they came from. For example, if I'm looking at `/classrooms/30`, and I press the `Back` button, it takes me to `/classrooms` as opposed to the site I originally navigated from.

As a suggestion, we may consider including some little flags in the URL's. For example, clicking on a link in the sidebar would add `?fromhomesidebar=true`, or, to be more concise, `?s=true`, to the URL that the user navigates to. Then, the system would change the links displayed on the page to actually redirect back, in this case, to the home page.

Another suggestion----one which does not require much work, at that----is to change all of the "Back" links to reflect where they actually go (i.e. "Back" on `classrooms#show` would be changed to "All Classrooms"). Additionally (and optionally), we could add a "Home" button to the `btn-group` at the bottom of all of the pages that would just redirect to the `docket#index` or `root_url`.

**Comment by Sammidysam** [comment]
I am pretty sure the back buttons are auto-generated, which causes this problem.  I would suggest multiple buttons over dealing with going back.

**Comment by rye** [comment]
Yeah. I'll probably spend some time changing the words from (for example, on `classrooms#show` "Back" to "All Classrooms"), which makes more sense either way.

**Comment by cg505** [comment]
I want the buttons to be going where they're going. Better names will probably help.

**Comment by cg505** [comment]
Creating `fix-button-names` to fix this.
