### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#4]
Our school docket is not only used for homework assignments and tests.  It is also used for listing events that occur during the school year.  For example, on December 20, 2013, the events were "First Semester Ends" and a basketball game.  This program will definitely need to display events to users.

Ideally, we could also go so far as to allow users to say that they are going to this event so that people can coordinate if their friends are going or not.  If that was implemented, the school system could get a faint idea of how many people are going to the event and plan accordingly (they would always have to plan higher than the number, of course).  This would be a lot of work likely and we can save it for later for sure.

By 0.1.0, we should allow adding events and displaying them in the docket.  We do not need to go much further than something like what the physical docket shows in that respect.

Later, we can add what the second paragraph addressed (though that would be a feature that we would add very late in development) and personal events vs. school events.  A user would be able to filter out the school events if they don't care what our school does.  We could also allow clubs, sports groups, and other groups around the school to schedule their own events.  Then the school events would only be events such as "First Semester Ends".

**Comment by cg505** [comment]
I think that this is almost definitely a good idea. However, we do need to keep in mind that we have a somewhat limited workforce and we need to be careful not to spread ourselves over too many frugal features.

~~I don't know if basic events will be able to happen for 0.1.0.~~ It actually shouldn't really be too hard, I might be able to do that tomorrow morning.

**Comment by Sammidysam** [comment]
Yeah, only displaying the list of events to the user does not sound hard to me.  The improvements will become hard, but I do not feel like basic events will have to be pushed to after 0.1.0.

**Comment by cg505** [comment]
This is now a part of the application that is developed along with assignments and exams. Closing.

**Comment by Sammidysam** [comment]
What exactly does that mean?

**Comment by rye** [comment]
Events have been added to some extent. If you want more functionality out of them, I suggest making a `feature request` issue for them.

**Comment by Sammidysam** [comment]
Oh, okay.  I thought that we kept the issues open until we had finished the whole issue, not just part of it.

**Comment by cg505** [comment]
Well, the reason I closed it is because at this point, events are developed along with assignments and exams, as a core part of the project. We don't have issues for assignments and exams, so I don't feel it makes a whole lot of sense to leave this open. However, I overlooked the fact that this issue has more info (about coordination and such). If you feel we should reopen it so that that doesn't get buried, please go ahead.

**Comment by Sammidysam** [comment]
I think we can just open an issue for all three of the things when our next minor version will focus on them, and then we can reference this issue in the description.  This can stay closed.
