### ISSUE TITLE
Plan for Release

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#40]
Considering that we seem to be approaching the release of `v0.2.0`, I would like to suggest that we finalize some stuff. I think the design changes (and the backend changes which accompanied them) will be enough to constitute the release, and we don't need to have that much more in it.

Are we good to merge `master` into `v0.2.0` and then `v0.2.0` into `master`? I'll handle all of the merge conflicts (I can sense that there will be plenty...), if that's okay.

@cg505? @Sammidysam?

**Comment by rye** [comment]
I'd like to do this this afternoon if that sounds okay, so I need responses from you people.

**Comment by cg505** [comment]
We people (at least I) will be rather busy until Monday. However, if
@Sammidysam gives a signoff, go ahead.

**Comment by rye** [comment]
So @Sammidysam, what do you think?

**Comment by Sammidysam** [comment]
I have added some other items to be in the 0.2.0 release, specifically docket views.  It very much pertains to the docket interface, so they should at least be added.  I can try to work on that this weekend possibly.

**Comment by Sammidysam** [comment]
We should wait until all 0.2.0 milestone issues are done before releasing 0.2.0.

**Comment by rye** [comment]
I'm still wanting to merge the changes (i.e. fixes) that were made and merged to `master` into `v0.2.0`, so we don't double-implement.

**Comment by Sammidysam** [comment]
You are free to merge master into any branch whenever you want.

**Comment by rye** [comment]
Considering that all of the milestone issues are complete, I'm going to bump this issue for re-evaluation.

Since every feature that was remaining besides the global events will be dependent (in the end) to some extent on the user's configuration, I decided that we should move them so that all of that gets done at once. It'll be much cleaner that way.

**Comment by rye** [comment]
Quickly checking, it doesn't seem that there are any glaring issues which will prevent a release from happening today. [EDIT: "(i.e. no merge conflicts)"]

**Comment by rye** [comment]
`**NOTICE**:` Version 0.2.0 will be released at approximately 15:00 this afternoon, unless there is disagreement.

**Comment by rye** [comment]
This has been merged. Drafting release now.
