### ISSUE TITLE
SMS/Twitter-based Assignment Creation?

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#43]
##### Introduction

For people like me who do not have access to the site from a mobile platform, it is inconvenient to have to wait until we have access to laptops or desktop computers.

While there are a few possible solutions on the user's end to this problem (namely getting a data plan), it would be great to have some sort of way to post these things through some sort of medium such as SMS.
##### Suggestion 0x0

The way I've suggested in the past is to create a Twitter account for the system. Not only would that enable us to have mobile DB input, it would also enable us to post announcements to the community of users or people who are interested in the project.

Twitter has support for Direct Messages, which enable the system to send and receive messages privately. The syntax for posting one of these over a SMS-verified connection is as follows:

```
DM @[account] [message contents]
```

To send @-tweets to a twitter account, it's as simple as this:

```
@[account] [message contents]
```

Alternatively, we could just keep a list of Twitter accounts that are verified and are allowed to post. Or, just add a field in the database to contain the user's Twitter username. Either way, we would filter all either direct messages or @-tweets by those usernames and figure out who is the user that is trying to post.
###### Necessary Things

The necessary features of this will be the support for all of the following:
- Identifying the user who is posting (for activity tracking).
- Selecting a class by class name, course number and hour, or otherwise.
- Selecting what type of thing to add (assignment, exam, or event).
- Leaving enough room for the title and description of the thing.
- Having a date/time.
##### Problems for Suggestion 0x0

Of course, we would need to figure out parsing this direct-message syntax. There appears to be a DM message size limit of 140 characters, just like the tweet size limit is. Size limits are a big issue here, and so we'll have to be extremely conscientious about how we use characters.
##### Syntax Brainstorming

This are some sample tweet layouts that we might deal with:

```
3064h:1:+a:Sample Assignment:This is a sample assignment:20140125
```

This should create an assignment (`+a`) "Sample Assignment" with the description "This is a sample assignment" under the class "3064H" (`3064h`) with the period "1" (`1`), with the due date 2014-01-25.

---

```
ch1h:1:+a:Sample Assignment:This is a sample assignment:20140125
```

This should create an assignment (`+a`) "Sample Assignment" with the description "This is a sample assignment" under the class that fuzzy-matches "ch1h" with the period "1" (`1`), with the due date 2014-01-25.

---

```
```

(more to come later)

**Comment by cg505** [comment]
Why is this closed?

**Comment by rye** [comment]
Lack of activity.

**Comment by Sammidysam** [comment]
That is no reason to close an issue, unless you have completely given up on ever doing the work for this.

**Comment by rye** [comment]
It's not really an "Issue" to begin with. I'll look at it later, but there shouldn't actually be called an "Issue", especially if it's just sitting there.

**Comment by Sammidysam** [comment]
Issues are things to look into for the program, i.e. a to-do list.

**Comment by rye** [comment]
That's not really the definition of "Issue."

**Comment by rye** [comment]
If you really want this issue to be open again, then go ahead and re-open it.

Hell, I'll do it for you.
