### ISSUE TITLE
Change docket to render simply the next 7 days

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#44]
This will get overwritten by the next merge with v0.3.0, as we'll add user configuration then. This makes viewing this on Friday and Saturday more useful.

**Comment by Sammidysam** [comment]
That sounds good to me.  As we do not currently indicate what day is today, it will definitely help.

**Comment by rye** [comment]
Actually we already do this.

**Comment by Sammidysam** [comment]
We do?  On master branch it does not look so.

**Comment by rye** [comment]
I'm pretty sure we use [this](https://github.com/kotct/docket/blob/f23da696b795c2e16acc3431cbcddaf1c2b799b2/app/helpers/application_helper.rb#L37-58) (it's on master--added at f23da696b795c2e16acc3431cbcddaf1c2b799b2). This was implemented at c230517deb0857f463988291caa22f4b554489e8

**Comment by Sammidysam** [comment]
Oh, yes, sorry.  I got confused by pronouns and thought that you were saying that we already indicate what day is today.  I remember a @cg505 commit that did that, though.
