### ISSUE TITLE
classrooms#show: assignment display fixes

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#46]
It appears that there are a number of problems with the existing system.
- We should probably not display assignments and exams from the past.
- We should actually display assignments and exams in the future.

Both of these things appear to be problems with the existing system.

I'll put this in `patch-v0.2.2`.

**Comment by rye** [comment]
It looks like we're just showing the first 3 or 5 in the array, which is horrible practice.

**Comment by rye** [comment]
An improvement would be to show **all** assignments and exams for the future, which is what I will do.

**Comment by rye** [comment]
Once rails is happy on `apps-development`, I'll take care of this.

**Comment by Sammidysam** [comment]
These are good fixes.

**Comment by rye** [comment]
All right, this is implemented. #52 requests merge to master.
