### ISSUE TITLE
classroom: "name" function's return value makes little sense

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#47]
Classroom names don't make sense when they've got a bunch of hyphens thrown in and things are in a weird order.

A better way to display it would be:

```
[n.ordinalize] hour "[class name]": [teacher name]
```

I'll take care of this.

**Comment by cg505** [comment]
I don't think the thing should be in quotes.

**Comment by rye** [comment]
You're welcome to change it.

**Comment by rye** [comment]
This is better now. I've included an `html` argument that is optional (defaults to `false`) which will generate HTML-safe stuff and return it if true (otherwise just the text that would be generated by it).

**Comment by rye** [comment]
This is implemented. #52 requests merge to master.
