### ISSUE TITLE
Screencasts

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#49]
Somewhat related to #48, we should make some screencasts to discuss how to use `docket`. This isn't as common as you would think, but outlining the basic infrastructure and basic navigational techniques would be nice.

Also, I think it would make some sense to have version-tied development screencasts--especially as we get into the `v1`'s and beyond, people may have interest in what has changed, so outlining these things would be good to do.

Screencasts in general are good because people generally like to watch videos as opposed to reading. We could record audio, but having on-screen visuals seems like a good idea.

**Comment by Sammidysam** [comment]
Do we want to wait until the first major release to start these?  I think that's a good idea.

**Comment by rye** [comment]
I would say we should make some for the pre-testers so they can understand what to do, but we should make more detailed and professional ones later on.

**Comment by rye** [comment]
I would recommend that we start writing org-mode files regarding this.

**Comment by Sammidysam** [comment]
We still have a long way to go before 1.0.0, and parts of the program may change.  Therefore, maybe we should wait.

**Comment by Sammidysam** [comment]
Actually, I forgot about your comment relating to making some for pre-testers.  It would be fine to plan some, then, but do not make it a big priority.

**Comment by rye** [comment]
Yeah. I'll just start writing outlines (perhaps on a `documentation-screencasts` branch or something similar).

**Comment by Sammidysam** [comment]
There is no need to have the preceding `documentation-`.  It is a waste of characters.

**Comment by rye** [comment]
That is correct.
