### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#5]
Can we use [SCSS](http://sass-lang.com/) instead of CSS?  I believe it would work if we renamed `application.css` to `application.css.scss`, though I am not entirely sure.  I remember having an application in which the main stylesheet was `application.css.scss`.  Either way, using SCSS instead of CSS will likely save time and allow us to modify our stylesheets easier in the future.

Also, `bootstrap-sass` incorporates with `scss` so that we can easily modify the Bootstrap.

In any case, this should wait until after 0.1.0 is finished.

**Comment by cg505** [comment]
I believe that the default in this project _is_ scss, it's just that the application stylesheet happens not to have the correct suffix. All the other stylesheets seem to have it right.

So yes, SCSS.

**Comment by Sammidysam** [comment]
Then we should just rename `application.css` to `application.css.scss` and close this, no?

**Comment by rye** [comment]
Basically.

**Comment by Sammidysam** [comment]
Yeah, the actual CSS code will need to be converted into SCSS before we can close this.  I will rename the file, and the code can be converted after we finish 0.1.0.

**Comment by cg505** [comment]
I'm not that familiar with SCSS... is valid CSS not valid SCSS?

**Comment by Sammidysam** [comment]
Renaming the file is done.  After 0.1.0 we can turn the CSS code into SCSS, and then we could release that as 0.1.1 possibly.  I feel like after we get to 0.1.0 whenever we make a bug fix or small change, as long as it isn't full of bugs, we should merge it and release a sub-sub-version.

**Comment by Sammidysam** [comment]
Valid CSS is valid SCSS.  [Here](http://nex-3.com/posts/96-scss-sass-is-a-css-extension) is a source that says so, if you would like one.

SCSS is pretty much SASS with CSS syntax.

**Comment by cg505** [comment]
I was thinking that a sub-sub-version would be either a rather urgent bug fix or one small feature or a slew of small bug fixes (maybe about an hour of work). How's that?

**Comment by Sammidysam** [comment]
That sounds good.  Yeah, I just realized that it probably is not worth releasing a sub-sub-version if nothing changes for the end user.

I think that small features might be supposed to tend towards sub-versions, though.

**Comment by rye** [comment]
Considering that we're using SCSS now, I'll close this issue.

**Comment by Sammidysam** [comment]
Nope, we still haven't transferred the CSS into SCSS in application.css.scss.
