### ISSUE TITLE
Email-Based Authentication

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#51]
Currently, many account-based things are done either by directly adding an account and then deleting or changing details about it in the future. One possible thing we could use is [SendGrid](http://sendgrid.com/) which I've heard many good things about. Email is more secure, and also is considered common practice.

**Comment by rye** [comment]
We should probably consider two-factor if anything.

**Comment by cg505** [comment]
Why is this closed?

**Comment by rye** [comment]
Lack of activity. Two-factor would be better.

**Comment by cg505** [comment]
They aren't mutually exclusive.

**Comment by rye** [comment]
Great, so reopen it. I'm not going to do it all by myself, and I'm not interested in email-based authentication because we'll need to pay money and stuff.

**Comment by rye** [comment]
Also SMS implementation would be difficult.
