### ISSUE TITLE
Some prettiness issues

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#53]
![docket-screencap-stuff](https://cloud.githubusercontent.com/assets/1581504/2621798/08294e40-bc6c-11e3-9a42-f0d9c08cd6b0.png)

Just a few thoughts I had.

**Comment by Sammidysam** [comment]
For moving in you mean both the flash and navbar, right?

**Comment by rye** [comment]
Yes, I think the navbar needs to be constrained in the same way that the flash and content areas are, or at least just the flash. I'll work on some icons.

**Comment by rye** [comment]
No, we're not incorporating icons from elsewhere.

**Comment by rye** [comment]
I disagree about the footer. We may want to link the wiki elsewhere, but asymmetry in this case isn't that disgusting to me.

**Comment by cg505** [comment]
Font awesome?

**Comment by rye** [comment]
Good idea.

**Comment by cg505** [comment]
On the navbar: two things.
1. Should we constrain it like the flash? I had not intended to imply that, but its not necessarily a bad idea.
2. Are we in agreement that it should be light-colored? I think the dark's contrast with the rest of the page is just too great.

**Comment by cg505** [comment]
To see what the light navbar looks like, checkout the `alt-navbar-color` branch.

**Comment by Sammidysam** [comment]
Yes and yes.

**Comment by cg505** [comment]
The only thing we have left is the weird footer icon/text combo. So, both icons or both text? I'll do some testing.

**Comment by cg505** [comment]
checkout branches `both-icons` and `both-text` and see which one you like better.
