### ISSUE TITLE
Plans

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#56]
What do we want this thing to do, exactly?

Planned Features
- API
- Two separate database schemas from which one can be chosen
  - Dedicated server
    - No support for multiple schools
  - Open server
    - Support for multiple schools
      - Each registered school will have a subdomain
- User can join classes that they are in
- User can enter assignments, exams, and events into the classes that they are in
- The user's docket will contain
  - Assignments from the classes that they are in
  - Exams from the classes that they are in
  - Events associated with their classes
  - Global events
  - Events that the user has joined
- User can create private assignments, exams, events, and notes which can also be associated with a class or not
  - [include `public:boolean` and allow `classroom_id` to be nil]
- User can create events
  - Event can be non-global, where a user will have to join event for it to show up on docket
    - Can also be associated with a class, where it will show up on the dockets of the members of that class
  - Event can be global, where it will always show up on a user's docket
- Assignments, exams, and events can be discussed via comments by members that have the corresponding object in their docket

**Comment by Sammidysam** [comment]
Should we have a Hangout about this sometime?

**Comment by rye** [comment]
No, comment with your ideas.

**Comment by rye** [comment]
Unless you're willing to wait 1+ week, which I most certainly am not.

**Comment by Sammidysam** [comment]
Ah, okay.  I was just curious because verbal communication is good for long discussions.  So shall all three of us write our idea of what this program should become, and then we create a concrete plan based upon that?

**Comment by rye** [comment]
Yes.

---

I think it should be like this:
- `docket` is accessible to any student in the world from any school.
- `docket` lets them connect to the classmates they work with on a daily basis.
- `docket` lets them enter in assignments, exams, and events, and share them with their classmates.
- `docket` also helps them keep themselves organized, letting them keep notes, ideas, and personal assignments, exams, and events.

I think our end goal should be flexible, but we have the basic gist; it's an organization tool. In general, we need to build to the world, not just West Lafayette High School. There're only so many people in WLHS who can actually use docket, and most people I know are so set in their old ways that it'd be a miracle if they used docket.

**Comment by Sammidysam** [comment]
I agree with all of those statements.  I think we all agree with the basic gist of it, but how we want to go about making the final product is where the debate arises.  On the point of connecting with classmates, does this mean that they can discuss assignments (assignments have comments)?  I seem to like that idea.

**Comment by rye** [comment]
I think that might raise legal problems if used incorrectly. I was talking more about how people could identify their classmates and then they could be given a suggestion as to which classes to join. I think most of our problems with being usable arise with the procedure for joining classes.

**Comment by Sammidysam** [comment]
People discuss assignments through external services, so I am not sure why they shouldn't be allowed to discuss them here.  I don't know about suggestions of which classes to join, that seems a bit weird.  Joining classes is not horribly difficult right now.

On the note on the actual program, do we want it to have a powerful API so that little desktop applications could be made if we have absolutely nothing to do with our time?  I think this is a good idea.  APIs are fun.

**Comment by cg505** [comment]
Under the current system, each school needs their own server, but the software will work for any school. Does that count as building to the world?

**Comment by rye** [comment]
@Sammidysam That is true. However, joining classes _is_ difficult, mainly because we don't make it plainly obvious to the people who sign up how to set up their account. An API would be good, especially if we want to write mobile apps as well.

@cg505 I'm not sure. I think it'd be nice if we supported multiple schools per server, because not all schools necessarily have the ability to have a docket server. It'd be nice if we had the ability to deploy this to an entire data center and have it function for everyone in the world.

**Comment by cg505** [comment]
IMO, ideally, we would have a domain (say, docket.com), and schools would use subdomains (for example, wlhs.docket.com). We could also allow CSS customization on a per-school basis and some other configuration features.

**Comment by rye** [comment]
I like those ideas, they make sense.

**Comment by Sammidysam** [comment]
Okay, so we agree that a powerful API will be a good goal to strive for.  I love your idea, @cg505.  We also want to allow for having one server dedicated to one school, however, because some schools may prefer that.  So do we need to look into two different schemas of which one will be chosen when the database is initialized?

**Comment by Sammidysam** [comment]
@krye: Is it fine if we edit the issue to add to a list of features that this program will entail?

**Comment by rye** [comment]
Yep.

**Comment by cg505** [comment]
Generally, subdomains would point to different servers or at least different instances on the same server.

**Comment by Sammidysam** [comment]
I think I just wrote down our current plan.  I may have added a tiny bit of stuff.

**Comment by rye** [comment]
@cg505 is correct about subdomains.

**Comment by Sammidysam** [comment]
Ah, okay, so our database will never need to account for multiple schools?

**Comment by rye** [comment]
Again I say, it would be nice if it supported multiple schools, but having one server isn't necessary. It'd be nice if there's a school field and everything that we have currently belongs to it. That way, if necessary, it would work in production.

**Comment by Sammidysam** [comment]
Ah, okay, so I am thinking that having two schemas to choose from sounds better.

**Comment by rye** [comment]
Not necessarily; it's perfectly fine to have just one school in the database. I think sacrificing the ease of the addition of another school to database for the sake of getting rid of a few trace queries is silly.
