### ISSUE TITLE
Design?

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#6]
What kinds of interface-y stuff do we want to do? What kind of colors should we use? Background colors? Text colors? Font colors? Fonts? Should we have über-fancy stuff?

EDIT: This thread will be used for dumping design-related questions.

**Comment by Sammidysam** [comment]
Do we want to use school colors which would make it seem more specific to our school?  We could also strive to make this a tool for many school besides ours, and opt out of using our school colors specifically.

**Comment by rye** [comment]
[duplicate, see #14]
