### ISSUE TITLE
Write a more full test suite.

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#62]
It'd be nice if we had coverage of all of the functions in the entire codebase, and if the test suite would actually pass on the "stable" code.

**Comment by rye** [comment]
@cg505, is it okay with you if I rip out the old test suite and write a new one? It'd make my life a bit easier, since there's a lot of fragmentation and I think it's a bit overcomplicated. If you want, you could explain how `spec/` is laid out now and I'd probably understand it and not want to rip it out any more.

**Comment by cg505** [comment]
YES. :ok_hand:

**Comment by rye** [comment]
Just to confirm, you want me to rip it out, right?

**Comment by cg505** [comment]
rip it out

**Comment by rye** [comment]
Groovy. I'm good at that.
