### ISSUE TITLE
Multiple-year database schema

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#66]
It might be a good idea to have the same database cover multiple years so that we don't have to drop the entire db every year. On the other hand, manually dropping (or even automating the dropping of) the db isn't that bad.

**Comment by rye** [comment]
I think that we could create a Rake task to update the DB for each year (e.g. getting rid of assignments, exams, events from the previous year, and classrooms, courses, and teachers that will've changed in the next year), then run it on the live deploy.

**Comment by Sammidysam** [comment]
History is fun to look back at.  I like looking at my old dockets and seeing what was going on in my life (if you have seen, I write on all of the space it gives me, and usually referring to more than just school).  I think that allowing multiple years or dropping the database depending on a configuration setting would be best.
