### ISSUE TITLE
View assignment and exams

### ISSUE THREAD

**Issue by Sammidysam** [kotct/docket-old#8]
Are assignments and exams supposed to be viewed?  I am not sure if I am just being dumb and they are "obviously" not set up or there is actually a bug.

Also, `classroom_id` in the assignments is always set to `nil`.
###### Images, in order of occurrence

http://s13.postimg.org/4mg2hhaon/Docket_Mozilla_Firefox_002.png
http://s13.postimg.org/qmwey3tcn/Docket_Mozilla_Firefox_003.png
http://s13.postimg.org/m2a8j69nb/Action_Controller_Exception_caught_Mozilla_Fi.png

**Comment by cg505** [comment]
Yes, they are set up. This is a bug. It's supposed to automatically set the classroom_id based on where you clicked the link. Looking into it.
